"""update birth_day

Revision ID: 213b6fbb3424
Revises: 4397cdee8ebb
Create Date: 2023-12-17 20:56:02.805682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '213b6fbb3424'
down_revision: Union[str, None] = '4397cdee8ebb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('birth_day', sa.DateTime(), nullable=True))
    op.drop_column('contacts', 'birthday')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('contacts', sa.Column('birthday', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('contacts', 'birth_day')
    # ### end Alembic commands ###
