"""add avatar

Revision ID: 2958500b681b
Revises: ce8dd774d1f1
Create Date: 2023-12-24 23:13:55.257235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2958500b681b'
down_revision: Union[str, None] = 'ce8dd774d1f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('administrator', 'moderator', 'user', name='role'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('administrator', 'moderator', 'user', name='role'),
               nullable=True)
    # ### end Alembic commands ###
