"""add role

Revision ID: 4397cdee8ebb
Revises: 5b6923a171f0
Create Date: 2023-12-17 19:44:51.559228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '4397cdee8ebb'
down_revision: Union[str, None] = '5b6923a171f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE role as ENUM('administrator', 'moderator', 'user')")
    op.add_column('users',
                  sa.Column('role', sa.Enum('administrator', 'moderator', 'user', name='role'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.execute("DROP TYPE role")
    # ### end Alembic commands ###
