"""migrate email

Revision ID: ce8dd774d1f1
Revises: 5a4c1dc18d1a
Create Date: 2023-12-24 17:08:22.850909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce8dd774d1f1'
down_revision: Union[str, None] = '5a4c1dc18d1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_contacts_email', table_name='contacts')
    op.drop_column('contacts', 'email')
    op.add_column('users', sa.Column('email', sa.String(length=150), nullable=False))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    op.add_column('contacts', sa.Column('email', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.create_index('ix_contacts_email', 'contacts', ['email'], unique=False)
    # ### end Alembic commands ###
